# Site settings

title: Slice Software
logo: "/assets/images/slice_logo.jpg"
email: joshua.shapiro@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Insights and ruminations on software development.
baseurl: "/slicesite" # the subpath of your site, e.g. /blog
url: "https://slicesoftware.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jns
author:
  name     : "Joshua Shapiro"
  bio      : "Software Architecture and Design"
  location : "San Diego, CA USA"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
